import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
// import { AuthContextProvider } from "@/context/AuthContext"
import React from "react"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Tinder Customers",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AuthContextProvider>{children} </AuthContextProvider> */}
        <div>{children} </div>
      </body>
    </html>
  )
}
